export const studentAptitudeQuestions = [
    {
        "section": "Numerical Reasoning",
        "text": "A sequence follows this rule: Each term is generated by combining the difference and ratio of the previous two terms alternately. \"3, 6, 9, 3, ___\"",
        "textMl": "താഴെ പറയുന്ന സംഖ്യകളുടെ ക്രമം (Sequence) ഒരു പ്രത്യേക നിയമം പാലിക്കുന്നു: ശരിയായ ഉത്തരം കണ്ടെത്തുക. \"3, 6, 9, 3, ___\"",
        "options": [
            {
                "text": "6",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "9",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "12",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "3",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Four machines together complete a task in 6 hours. Two of them stop after 2 hours. The remaining two finish the task in 10 more hours. Which statement is logically true?",
        "textMl": "നാല് മെഷീനുകൾ ചേർന്ന് ഒരു ജോലി 6 മണിക്കൂർ കൊണ്ട് തീർക്കുന്നു. 2 മണിക്കൂർ കഴിഞ്ഞപ്പോൾ രണ്ട് മെഷീനുകൾ പണി നിർത്തി. ബാക്കിയുള്ള രണ്ട് മെഷീനുകൾ ആ ജോലി തീർക്കാൻ പിന്നെയും 10 മണിക്കൂർ കൂടി എടുത്തു. എങ്കിൽ താഴെ പറയുന്നതിൽ ശരിയായ പ്രസ്താവന ഏതാണ്?",
        "options": [
            {
                "text": "All machines work at equal efficiency",
                "textMl": "എല്ലാ മെഷീനുകൾക്കും ഒരേ വേഗതയായിരുന്നു",
                "isCorrect": false
            },
            {
                "text": "The stopped machines were faster",
                "textMl": "പണി നിർത്തിയ മെഷീനുകൾക്ക് കൂടുതൽ വേഗത ഉണ്ടായിരുന്നു",
                "isCorrect": false
            },
            {
                "text": "Remaining machines are slower than the initial average",
                "textMl": "ബാക്കിയുള്ള മെഷീനുകൾക്ക് ആദ്യത്തെ ശരാശരി വേഗതയേക്കാൾ കുറവാണ്",
                "isCorrect": true
            },
            {
                "text": "Cannot be determined",
                "textMl": "കൃത്യമായി പറയാൻ പറ്റില്ല",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "A number is multiplied by 4, then 12 is subtracted. The result is equal to triple the original number plus 6. What is the number?",
        "textMl": "ഒരു സംഖ്യയെ 4 കൊണ്ട് ഗുണിച്ചു, അതിൽ നിന്ന് 12 കുറച്ചു. കിട്ടിയ ഉത്തരം ആ സംഖ്യയുടെ മൂന്നിരട്ടിയോടൊപ്പം 6 കൂട്ടുന്നതിന് തുല്യമാണ്. എങ്കിൽ ആ സംഖ്യ ഏതാണ്?",
        "options": [
            {
                "text": "6",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "9",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "12",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "18",
                "textMl": "",
                "isCorrect": true
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Which option completes the pattern? 2 → 6 → 18 → ? → 162",
        "textMl": "ഈ ക്രമം പൂർത്തിയാക്കാൻ അടുത്ത സംഖ്യ ഏതാണ് വേണ്ടത്? 2 → 6 → 18 → ? → 162",
        "options": [
            {
                "text": "36",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "54",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "72",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "81",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "If all Zogs are Tals and some Tals are Rims, which is true?",
        "textMl": "എല്ലാ 'ജോഗുകളും' (Zogs) 'ടാലുകൾ' (Tals) ആണെന്നും, ചില 'ടാലുകൾ' 'റിമ്മുകൾ' (Rims) ആണെന്നും കരുതുക. എങ്കിൽ താഴെ പറയുന്നതിൽ ഏതാണ് ശരി?",
        "options": [
            {
                "text": "All Zogs are Rims",
                "textMl": "എല്ലാ ജോഗുകളും റിമ്മുകൾ ആണ്",
                "isCorrect": false
            },
            {
                "text": "Some Zogs may be Rims",
                "textMl": "ചില ജോഗുകൾ റിമ്മുകൾ ആയേക്കാം",
                "isCorrect": true
            },
            {
                "text": "No Zogs are Rims",
                "textMl": "ജോഗുകൾ ഒന്നും റിമ്മുകൾ അല്ല",
                "isCorrect": false
            },
            {
                "text": "All Rims are Zogs",
                "textMl": "എല്ലാ റിമ്മുകളും ജോഗുകൾ ആണ്",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "A number increases by 20%, then the result decreases by 20%. The final value is:",
        "textMl": "ഒരു സംഖ്യ ആദ്യം 20% കൂടി, പിന്നെ ആ പുതിയ സംഖ്യയിൽ നിന്ന് 20% കുറഞ്ഞു. എങ്കിൽ അവസാന കിട്ടിയ സംഖ്യ:",
        "options": [
            {
                "text": "Same as original",
                "textMl": "ആദ്യത്തെ സംഖ്യ തന്നെ",
                "isCorrect": false
            },
            {
                "text": "Higher",
                "textMl": "കൂടുതലായിരിക്കും",
                "isCorrect": false
            },
            {
                "text": "Lower",
                "textMl": "കുറവായിരിക്കും",
                "isCorrect": true
            },
            {
                "text": "Cannot be predicted",
                "textMl": "പറയാൻ പറ്റില്ല",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Which option has the same logical structure as: “Half of X plus one-third of X equals five-sixths of X”?",
        "textMl": "\"X- ന്റെ പകുതിയും X- ന്റെ മൂന്നിലൊന്നും കൂട്ടിയാൽ X- ന്റെ ആറിൽ അഞ്ച് ഭാഗം കിട്ടും\" - ഇതിന് സമാനമായ ലോജിക് ഏതാണ്?",
        "options": [
            {
                "text": "2/4 + 1/6 = 5/6",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "3/6 + 2/6 = 5/6",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "1/2 + 1/3 = 5/6",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "4/6 + 1/6 = 5/6",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "If A > B > C and D < C, which must be true?",
        "textMl": "A എന്നത് B- യേക്കാൾ വലുതും, B എന്നത് C- യേക്കാൾ വലുതുമാണ്. D എന്നത് C- യേക്കാൾ ചെറുതുമാണ്. എങ്കിൽ ഇതിൽ ഏതാണ് തീർച്ചയായും ശരി?",
        "options": [
            {
                "text": "D < A",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "D > A",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "B < D",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "C < A",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Which situation represents exponential growth?",
        "textMl": "ഇതിൽ ഏത് സാഹചര്യമാണ് 'എക്സ്പോണൻഷ്യൽ വളർച്ച' (Exponential growth) കാണിക്കുന്നത്?",
        "options": [
            {
                "text": "Salary increases by ₹1000 yearly (ശമ്പളം എല്ലാ വർഷവും ₹1000 വീതം കൂടുന്നു)",
                "textMl": "ശമ്പളം എല്ലാ വർഷവും ₹1000 വീതം കൂടുന്നു",
                "isCorrect": false
            },
            {
                "text": "Savings double every year",
                "textMl": "സമ്പാദ്യം എല്ലാ വർഷവും ഇരട്ടിയാകുന്നു",
                "isCorrect": true
            },
            {
                "text": "Distance increases by 10 km daily (ദൂരം എല്ലാ ദിവസവും 10 കി. മീ വീതം കൂടുന്നു)",
                "textMl": "ദൂരം എല്ലാ ദിവസവും 10 കി. മീ വീതം കൂടുന്നു",
                "isCorrect": false
            },
            {
                "text": "Weight increases linearly",
                "textMl": "ഭാരം ഒരേ രീതിയിൽ കൂടുന്നു",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "If 5 people complete 40 units of work in 8 days, how many units per person per day?",
        "textMl": "5 ആളുകൾ ചേർന്ന് 8 ദിവസം കൊണ്ട് 40 യൂണിറ്റ് ജോലി തീർത്താൽ, ഒരാൾ ഒരു ദിവസം എത്ര യൂണിറ്റ് ജോലി ചെയ്യുന്നുണ്ടാകും?",
        "options": [
            {
                "text": "1",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "8",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "25",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "2",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "All thinkers question assumptions. Some scientists are thinkers. Which is logically valid?",
        "textMl": "ചിന്തിക്കുന്നവരെല്ലാം കാര്യങ്ങളെ ചോദ്യം ചെയ്യുന്നവരാണ്. ചില ശാസ്ത്രജ്ഞർ ചിന്തിക്കുന്നവരാണ്. എങ്കിൽ താഴെ പറയുന്നതിൽ ശരിയായ പ്രസ്താവന ഏതാണ്?",
        "options": [
            {
                "text": "All scientists question assumptions",
                "textMl": "എല്ലാ ശാസ്ത്രജ്ഞരും ചോദ്യം ചെയ്യുന്നവരാണ്",
                "isCorrect": false
            },
            {
                "text": "Some scientists question assumptions",
                "textMl": "ചില ശാസ്ത്രജ്ഞർ ചോദ്യം ചെയ്യുന്നവരാണ്",
                "isCorrect": true
            },
            {
                "text": "No scientists question assumptions",
                "textMl": "ശാസ്ത്രജ്ഞരാരും ചോദ്യം ചെയ്യാറില്ല",
                "isCorrect": false
            },
            {
                "text": "All thinkers are scientists",
                "textMl": "ചിന്തിക്കുന്നവരെല്ലാം ശാസ്ത്രജ്ഞരാണ്",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "\"Resilient\" is to \"stress\" as \"elastic\" is to:",
        "textMl": "'റെസിലിയൻസ്' (Resilient) എന്നത് 'സ്ട്രെസ്സിനോട്' (stress) എങ്ങനെ ബന്ധപ്പെട്ടിരിക്കുന്നുവോ, അതുപോലെ 'ഇലാസ്റ്റിക്' (elastic) എന്നത് എന്തിനോടാണ് ബന്ധപ്പെട്ടിരിക്കുന്നത്?",
        "options": [
            {
                "text": "Pressure",
                "textMl": "മർദ്ദം",
                "isCorrect": false
            },
            {
                "text": "Weight",
                "textMl": "ഭാരം",
                "isCorrect": false
            },
            {
                "text": "Stretch",
                "textMl": "വലിവ്",
                "isCorrect": true
            },
            {
                "text": "Shape",
                "textMl": "ആകൃതി",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Choose the statement that best completes the argument: \"Critical thinking improves decisions because…\"",
        "textMl": "\"ആഴത്തിലുള്ള ചിന്ത (Critical thinking) തീരുമാനങ്ങൾ മെച്ചപ്പെടുത്താൻ സഹായിക്കുന്നു, കാരണം...\" - താഴെ പറയുന്നതിൽ ഏതാണ് ഈ വാചകം പൂർത്തിയാക്കാൻ ഏറ്റവും അനുയോജ്യം?",
        "options": [
            {
                "text": "It increases intelligence",
                "textMl": "ഇത് ബുദ്ധി കൂട്ടുന്നു",
                "isCorrect": false
            },
            {
                "text": "It reduces emotions",
                "textMl": "ഇത് വികാരങ്ങൾ കുറയ്ക്കുന്നു",
                "isCorrect": false
            },
            {
                "text": "It evaluates evidence and alternatives",
                "textMl": "ഇത് തെളിവുകളും മറ്റ് വഴികളും പരിശോധിക്കുന്നു",
                "isCorrect": true
            },
            {
                "text": "It speeds up thinking",
                "textMl": "ഇത് ചിന്തയുടെ വേഗത കൂട്ടുന്നു",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": ": Identify the odd relationship:",
        "textMl": ": കൂട്ടത്തിൽ പെടാത്ത ബന്ധം (Odd Relationship) ഏതാണ്?",
        "options": [
            {
                "text": ": Doctor : Hospital (ഡോക്ടർ : ഹോസ്പിറ്റൽ)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Teacher : School (ടീച്ചർ : സ്കൂൾ)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Pilot : Airport (പൈലറ്റ് : എയർപോർട്ട്)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Farmer : Crops (കർഷകൻ : കൃഷി)",
                "textMl": "",
                "isCorrect": true
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Which sentence weakens the claim: \"Online learning always improves academic outcomes\"?",
        "textMl": "\"ഓൺലൈൻ പഠനം എല്ലായ്പ്പോഴും പഠനനിലവാരം മെച്ചപ്പെടുത്തുന്നു\" - ഈ വാദത്തെ എതിർക്കുന്ന വാചകം ഏതാണ്?",
        "options": [
            {
                "text": "Some students prefer classroom learning",
                "textMl": "ചില കുട്ടികൾക്ക് ക്ലാസ് റൂമിലിരുന്നു പഠിക്കാനാണ് ഇഷ്ടം",
                "isCorrect": false
            },
            {
                "text": "Internet access varies across regions",
                "textMl": "ഇന്റർനെറ്റ് സൗകര്യം എല്ലാ സ്ഥലങ്ങളിലും ഒരുപോലെയല്ല",
                "isCorrect": true
            },
            {
                "text": "Motivation affects learning",
                "textMl": "താല്പര്യം ഉണ്ടെങ്കിലേ നന്നായി പഠിക്കാൻ പറ്റൂ",
                "isCorrect": false
            },
            {
                "text": "Teachers use different methods",
                "textMl": "ഓരോ ടീച്ചറും ഓരോ രീതിയിലാണ് പഠിപ്പിക്കുന്നത്",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": ": Which assumption is necessary? “Company profits rose after flexible work hours were introduced.”",
        "textMl": ": \"ജോലി സമയത്തിൽ മാറ്റം വരുത്തിയതിന് ശേഷം കമ്പനിയുടെ ലാഭം കൂടി.\" - ഈ വാചകത്തിൽ മറഞ്ഞിരിക്കുന്ന ശരിയായ കാര്യം ഏതാണ്?",
        "options": [
            {
                "text": "Employees worked fewer hours",
                "textMl": "ജീവനക്കാർ കുറഞ്ഞ സമയം ജോലി ചെയ്തു",
                "isCorrect": false
            },
            {
                "text": "Flexible hours improve productivity",
                "textMl": "സമയ മാറ്റിയത് ഉൽപ്പാദനക്ഷമത കൂട്ടി",
                "isCorrect": false
            },
            {
                "text": "No other external changes occurred",
                "textMl": "ലാഭം കൂടാൻ മറ്റ് കാരണങ്ങളൊന്നും അപ്പോൾ ഉണ്ടായിരുന്നില്ല",
                "isCorrect": true
            },
            {
                "text": "Profits always rise",
                "textMl": "ലാഭം എപ്പോഴും കൂടിക്കൊണ്ടിരിക്കും",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": ": Choose the strongest inference: “Most creative people experiment frequently.”",
        "textMl": ": \"സർഗ്ഗാത്മകതയുള്ള (Creative) മിക്ക ആളുകളും പുതിയ കാര്യങ്ങൾ പരീക്ഷിച്ചു നോക്കാറുണ്ട്.\" - ഇതിൽ നിന്ന് മനസ്സിലാക്കാൻ പറ്റുന്ന കാര്യം എന്താണ്?",
        "options": [
            {
                "text": "All experimenters are creative",
                "textMl": "പരീക്ഷണങ്ങൾ നടത്തുന്നവരെല്ലാം സർഗ്ഗാത്മകതയുള്ളവരാണ്",
                "isCorrect": false
            },
            {
                "text": "Creativity requires experimentation",
                "textMl": "പരീക്ഷണങ്ങൾ ഉണ്ടെങ്കിൽ മാത്രമേ സർഗ്ഗാത്മകത ഉണ്ടാകൂ",
                "isCorrect": false
            },
            {
                "text": "Experimentation is linked to creativity",
                "textMl": "സർഗ്ഗാത്മകതയും പരീക്ഷണങ്ങളും തമ്മിൽ ബന്ധമുണ്ട്",
                "isCorrect": true
            },
            {
                "text": "Creativity is rare",
                "textMl": "സർഗ്ഗാത്മകതയുള്ളവർ കുറവാണ്",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": ": Which sentence contradicts: “Efficiency requires careful planning”?",
        "textMl": ": \"മികച്ച രീതിയിൽ ജോലി ചെയ്യാൻ കൃത്യമായ പ്ലാനിംഗ് വേണം\" - ഇതിന് വിരുദ്ധമായ വാചകം ഏതാണ്?",
        "options": [
            {
                "text": "Planning reduces errors",
                "textMl": "പ്ലാനിംഗ് തെറ്റുകൾ കുറയ്ക്കും",
                "isCorrect": false
            },
            {
                "text": "Efficiency improves speed",
                "textMl": "കാര്യക്ഷമത വേഗത കൂട്ടും",
                "isCorrect": false
            },
            {
                "text": "Careless work is inefficient",
                "textMl": "ശ്രദ്ധയില്ലാത്ത ജോലി മോശമാകും",
                "isCorrect": false
            },
            {
                "text": "Efficiency can exist without planning",
                "textMl": "പ്ലാനിംഗ് ഇല്ലെങ്കിലും മികച്ച രീതിയിൽ ജോലി ചെയ്യാം",
                "isCorrect": true
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": ": Which pair shares the same relationship? Idea : Innovation",
        "textMl": ": 'ഐഡിയ : കണ്ടുപിടുത്തം' (Idea : Innovation) എന്ന ബന്ധത്തിന് സമാനമായത് ഏതാണ്?",
        "options": [
            {
                "text": ": Seed : Plant (വിത്ത് : ചെടി)",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Plan : Success (പ്ലാൻ : വിജയം)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Theory : Practice (സിദ്ധാന്തം : പ്രായോഗികം)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Word : Sentence (വാക്ക് : വാചകം)",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": ": Which conclusion follows logically? “If data is inaccurate, conclusions may be flawed.”",
        "textMl": ": \"വിവരങ്ങൾ തെറ്റാണെങ്കിൽ, നിഗമനങ്ങളും തെറ്റായേക്കാം.\" - ഇതിൽ നിന്ന് ശരിയായി പറയാൻ പറ്റുന്നത് ഏതാണ്?",
        "options": [
            {
                "text": "Accurate data guarantees success",
                "textMl": "ശരിയായ വിവരങ്ങൾ ഉണ്ടെങ്കിൽ വിജയം ഉറപ്പാണ്",
                "isCorrect": false
            },
            {
                "text": "Flawed conclusions come only from bad data",
                "textMl": "തെറ്റായ നിഗമനങ്ങൾ മോശം വിവരങ്ങൾ കൊണ്ട് മാത്രമേ ഉണ്ടാകൂ",
                "isCorrect": false
            },
            {
                "text": "Data accuracy affects reliability",
                "textMl": "വിവരങ്ങളുടെ കൃത്യത അത് എത്രത്തോളം വിശ്വസിക്കാം എന്നതിനെ ബാധിക്കും",
                "isCorrect": true
            },
            {
                "text": "Data is always reliable",
                "textMl": "വിവരങ്ങൾ എപ്പോഴും വിശ്വസിക്കാൻ പറ്റുന്നതാണ്",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which shape completes the pattern?",
        "textMl": "ഈ പാറ്റേൺ പൂർത്തിയാക്കാൻ അടുത്തത് ഏത് ആകൃതി വരണം?",
        "options": [
            {
                "text": "●",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "▲",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "■",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "◆",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If follows a rule, which comes next? ⬤ ⬜ ⬤ ⬜ ⬜ ⬤ ⬜ ⬤ ⬤ ⬜ ____?",
        "textMl": "ഈ ക്രമത്തിൽ അടുത്തത് ഏതാണ് വരേണ്ടത്? ⬤ ⬜ ⬤ ⬜ ⬜ ⬤ ⬜ ⬤ ⬤ ⬜ ____?",
        "options": [
            {
                "text": "⬤",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "⬜",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Both",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Cannot be determined",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which option does NOT belong?",
        "textMl": "കൂട്ടത്തിൽ പെടാത്തത് ഏതാണ്?",
        "options": [
            {
                "text": "△ (Triangle)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "⬠ (Pentagon)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "⬢ (Hexagon)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "◯ (Circle)",
                "textMl": "",
                "isCorrect": true
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If A → C, B → D, C → F, then D → ?",
        "textMl": "A എന്നത് C- യായും, B എന്നത് D- യായും, C എന്നത് F- ആയും മാറുകയാണെങ്കിൽ, D എന്തായി മാറും?",
        "options": [
            {
                "text": "G",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "H",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "I",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "J",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Square : Cube :: Circle : ?",
        "textMl": "സ്ക്വയർ : ക്യൂബ് ആണെങ്കിൽ, സർക്കിൾ : ?",
        "options": [
            {
                "text": "Sphere",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Cone",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Cylinder",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Oval",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If pattern complexity doubles every step, which option fits next? + ++ ++++ ++++++ ?",
        "textMl": "ഓരോ ഘട്ടത്തിലും പാറ്റേണിന്റെ വലിപ്പം ഇരട്ടിയാവുകയാണെങ്കിൽ, അടുത്തത് ഏതാണ് വരുക? + ++ ++++ ++++++ ?",
        "options": [
            {
                "text": "+",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "++",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "++++",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "++++++",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which option completes the sequence of transformations? Rotate → Flip → Rotate → ?",
        "textMl": "മാറ്റങ്ങളുടെ ഈ ക്രമത്തിൽ അടുത്തത് ഏതാണ് വരേണ്ടത്? കറങ്ങുക → മറിക്കുക → കറങ്ങുക → ?",
        "options": [
            {
                "text": "Flip",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Scale",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Reflect",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Reverse",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If all Blips are Plips and no Plips are Slips, which is true?",
        "textMl": "എല്ലാ 'ബ്ലിപ്പുകളും' 'പ്ലിപ്പുകൾ' ആണെന്നും, പ്ലിപ്പുകൾ ഒന്നും 'സ്ലിപ്പുകൾ' അല്ലെന്നും കരുതുക. എങ്കിൽ ഏതാണ് ശരി?",
        "options": [
            {
                "text": "No Blips are Slips",
                "textMl": "ബ്ലിപ്പുകൾ ഒന്നും സ്ലിപ്പുകൾ അല്ല",
                "isCorrect": true
            },
            {
                "text": "All Slips are Blips",
                "textMl": "എല്ലാ സ്ലിപ്പുകളും ബ്ലിപ്പുകളാണ്",
                "isCorrect": false
            },
            {
                "text": "Some Slips are Blips",
                "textMl": "ചില സ്ലിപ്പുകൾ ബ്ലിപ്പുകളാണ്",
                "isCorrect": false
            },
            {
                "text": "All Blips are Slips",
                "textMl": "എല്ലാ ബ്ലിപ്പുകളും സ്ലിപ്പുകളാണ്",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which pattern uses two simultaneous rules?",
        "textMl": "ഒരേ സമയം രണ്ട് നിയമങ്ങൾ (Rules) ഉപയോഗിച്ചിരിക്കുന്ന പാറ്റേൺ ഏതാണ്?",
        "options": [
            {
                "text": "▲ ■ ▲ ■",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "2",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "4",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "6",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which option best completes a novel, unfamiliar rule set?",
        "textMl": "പരിചയമില്ലാത്ത ഒരു പുതിയ നിയമം (Rule set) പൂർത്തിയാക്കാൻ ഇതിൽ ഏതാണ് നല്ലത്?",
        "options": [
            {
                "text": "Option with repetition",
                "textMl": "ആവർത്തനമുള്ള രൂപം",
                "isCorrect": false
            },
            {
                "text": "Option with balanced variation",
                "textMl": "കൃത്യമായ വ്യത്യാസങ്ങളുള്ള രൂപം",
                "isCorrect": true
            },
            {
                "text": "Option with randomness",
                "textMl": "ക്രമമില്ലാത്ത രൂപം",
                "isCorrect": false
            },
            {
                "text": "Option with no pattern",
                "textMl": "പാറ്റേൺ ഇല്ലാത്ത രൂപം",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which object results from rotating a cube 90° vertically?",
        "textMl": "ഒരു ക്യൂബ് (Cube) 90 ഡിഗ്രി ലംബമായി തിരിച്ചാൽ എന്ത് സംഭവിക്കും?",
        "options": [
            {
                "text": "Same faces visible",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Opposite faces visible",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Adjacent faces visible",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "One face disappears",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "If a folded paper with two holes is unfolded, how many holes appear?",
        "textMl": "രണ്ട് ദ്വാരങ്ങളുള്ള ഒരു കടലാസ് മടക്കി വെച്ചിരിക്കുന്നു. അത് തുറക്കുമ്പോൾ എത്ര ദ്വാരങ്ങൾ കാണാൻ സാധ്യതയുണ്ട്?",
        "options": [
            {
                "text": "2",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "4",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "6",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "8",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which net forms a cube?",
        "textMl": "ഒരു ക്യൂബ് (Cube) ഉണ്ടാക്കാൻ ഇതിൽ ഏത് രീതിയിലുള്ള കടലാസ് കഷ്ണമാണ് (Net) വേണ്ടത്?",
        "options": [
            {
                "text": "Cross-shaped net",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Straight strip of 6 squares",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Zigzag pattern (സിഗ്-സാഗ് ആകൃതിയിലുള്ളത്)",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Random arrangement",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which shape is a mirror image of a right-facing 'L'?",
        "textMl": "വലത്തോട്ട് തിരിഞ്ഞിരിക്കുന്ന 'L' എന്ന അക്ഷരത്തിന്റെ കണ്ണാടിയിലെ രൂപം (Mirror image) ഏതായിരിക്കും?",
        "options": [
            {
                "text": "Same 'L'",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Reversed 'L' (ഇടത്തോട്ട് തിരിഞ്ഞ 'L')",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Upside down 'L' (തലതിരിഞ്ഞ 'L')",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Circle",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "If a staircase is viewed from directly above, what shape appears?",
        "textMl": "ഒരു ഗോവണി (Staircase) നേരെ മുകളിൽ നിന്ന് നോക്കിയാൽ എന്ത് ആകൃതിയിലാണ് കാണുക?",
        "options": [
            {
                "text": "Triangle",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Spiral",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Rectangle/Grid (ചതുരങ്ങൾ / ഗ്രിഡ്)",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Circle",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which direction results after: North → Right → Left → Right?",
        "textMl": "ഒരാൾ വടക്കോട്ട് നടക്കുന്നു → വലത്തോട്ട് തിരിയുന്നു → ഇടത്തോട്ട് തിരിയുന്നു → വീണ്ടും വലത്തോട്ട് തിരിയുന്നു. ഇപ്പോൾ അയാൾ ഏത് വശത്തേക്കാണ് നടക്കുന്നത്?",
        "options": [
            {
                "text": "North",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "East",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "South",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "West",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which solid has the most edges?",
        "textMl": "താഴെ പറയുന്നവയിൽ ഏറ്റവും കൂടുതൽ വശങ്ങൾ (Edges) ഉള്ളത് ഏതിനാണ്?",
        "options": [
            {
                "text": "Cube",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Pyramid",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Sphere",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Cylinder",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "If a point light source is directly above a cone, what is the shape of the shadow?",
        "textMl": "ഒരു കോണിന്റെ (Cone) നേരെ മുകളിൽ വെളിച്ചം അടിച്ചാൽ താഴെ വീഴുന്ന നിഴലിന്റെ ആകൃതി എന്തായിരിക്കും?",
        "options": [
            {
                "text": "Triangle",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Square",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Circle",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Rectangle",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which arrangement fits a space exactly without gaps or overlaps?",
        "textMl": "ഇടയിൽ വിടവുകളില്ലാതെ കൃത്യമായി അടുക്കി വെക്കാൻ പറ്റുന്ന രീതി ഏതാണ്?",
        "options": [
            {
                "text": "Overlapping shapes",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Gaps between shapes",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Perfect tessellation",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Random placement",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which transformation moves a shape's position without altering its orientation or view?",
        "textMl": "ഒരു ആകൃതിയുടെ ദിശ മാറ്റാതെ അതിന്റെ സ്ഥാനം മാത്രം മാറുന്നതിനെ (Transformation) എന്ത് പറയുന്നു?",
        "options": [
            {
                "text": "Translation (ട്രാൻസ്‌ലേഷൻ)",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Reflection",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Rotation",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Scaling",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If Gear A turns clockwise, Gear B (connected directly) turns:",
        "textMl": "ഗിയർ A ക്ലോക്ക് വൈസ് (Clockwise) ആയി കറങ്ങുകയാണെങ്കിൽ, അതിനോട് നേരിട്ട് ചേർന്നിരിക്കുന്ന ഗിയർ B എങ്ങനെ കറങ്ങും?",
        "options": [
            {
                "text": "Clockwise",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Anti-clockwise",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Faster",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Slower",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which tool best increases force with less effort?",
        "textMl": "കുറഞ്ഞ പ്രയത്നം കൊണ്ട് കൂടുതൽ ബലം പ്രയോഗിക്കാൻ സഹായിക്കുന്ന ഉപകരണം ഏതാണ്?",
        "options": [
            {
                "text": "Lever",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Rope",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Wheel",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Pulley",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If water flows faster through a narrow pipe, the relative pressure:",
        "textMl": "ഒരു ഇടുങ്ങിയ പൈപ്പിലൂടെ വെള്ളം കൂടുതൽ വേഗതയിൽ ഒഴുകുമ്പോൾ അവിടുത്തെ മർദ്ദം (Pressure):",
        "options": [
            {
                "text": "Increases",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Decreases",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Remains same",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Stops",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which setup lifts a load most efficiently?",
        "textMl": "ഭാരം ഉയർത്താൻ ഏറ്റവും എളുപ്പമുള്ള (Efficient) വഴി ഏതാണ്?",
        "options": [
            {
                "text": "Single rope",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Fixed pulley",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Movable pulley system",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "No pulley",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If friction increases between two surfaces, motion becomes:",
        "textMl": "രണ്ട് വസ്തുക്കൾക്കിടയിലുള്ള ഉരസൽ (Friction) കൂടിയാൽ, അവയുടെ ചലനം:",
        "options": [
            {
                "text": "Faster",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Unchanged",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Harder",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Impossible",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which factor affects structural stability most?",
        "textMl": "ഒരു നിർമ്മിതിയുടെ സ്ഥിരതയെ (Stability) ഏറ്റവും കൂടുതൽ ബാധിക്കുന്നത് എന്താണ്?",
        "options": [
            {
                "text": "Height",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Base width and Center of Gravity",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Color",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Material",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If one support fails in a redundant structure, what happens?",
        "textMl": "ഒന്നിൽ കൂടുതൽ താങ്ങുകളുള്ള ഒരു നിർമ്മിതിയിൽ ഒരെണ്ണം തകർന്നാൽ എന്ത് സംഭവിക്കും?",
        "options": [
            {
                "text": "Stable",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Collapses partially/Redistributes load",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Stronger",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Unchanged",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which increases speed without increasing input effort?",
        "textMl": "പ്രയത്നം കൂട്ടാതെ വേഗത കൂട്ടാൻ ഇതിൽ ഏതാണ് സഹായിക്കുക?",
        "options": [
            {
                "text": "Heavier load",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Better alignment/Lower friction",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Rough surface",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Smaller wheel",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If energy is conserved, efficiency losses typically occur as:",
        "textMl": "ഊർജ്ജം നഷ്ടപ്പെടുമ്പോൾ അത് സാധാരണയായി ഏത് രൂപത്തിലാണ് പുറത്തുപോകാറുള്ളത്?",
        "options": [
            {
                "text": "Light only",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Sound only",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Heat and sound",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Mass disappearing",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which change improves system output most effectively?",
        "textMl": "ഒരു മെഷീന്റെ പ്രവർത്തനം ഏറ്റവും നന്നായി മെച്ചപ്പെടുത്താൻ ഇതിൽ ഏതാണ് സഹായിക്കുക?",
        "options": [
            {
                "text": "Random adjustment",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Reducing friction",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Increasing weight",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Increasing resistance",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Identify the matching pair quickly: AB | BA | AC | CA",
        "textMl": "താഴെ പറയുന്നവയിൽ ജോഡികളായി വരുന്നത് വേഗത്തിൽ കണ്ടെത്തുക: AB | BA | AC | CA",
        "options": [
            {
                "text": "AB–BA",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "AC–CA",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "AB–AC",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "BA–CA",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which symbol appears most frequently in this set: \"[ ● ★ ● ■ ● ▲ ● ]?\"",
        "textMl": "ഈ കൂട്ടത്തിൽ ഏറ്റവും കൂടുതൽ തവണ കാണുന്ന ചിഹ്നം ഏതാണ്: \"[ ● ★ ● ■ ● ▲ ● ]?\"",
        "options": [
            {
                "text": "★",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "●",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "▲",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "■",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which number breaks the pattern? 7 14 21 28 35 43",
        "textMl": "ഈ ക്രമത്തിൽ തെറ്റായ സംഖ്യ ഏതാണ്? 7 14 21 28 35 43",
        "options": [
            {
                "text": "21",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "28",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "35",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "43",
                "textMl": "",
                "isCorrect": true
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Count the total triangles in a standard six-pointed star.",
        "textMl": "ആറ് കോണുകളുള്ള ഒരു നക്ഷത്രത്തിൽ ആകെ എത്ര ത്രികോണങ്ങൾ ഉണ്ട്?",
        "options": [
            {
                "text": "6",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "8",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "10",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "12",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which pair is identical?",
        "textMl": "താഴെ പറയുന്നതിൽ ഒരേപോലെയുള്ളത് ഏതാണ്?",
        "options": [
            {
                "text": "AX9 / A9X",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "B7C / B7C",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "9XA / XA9",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "C8B / 8CB",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Spot the odd one quickly:",
        "textMl": "കൂട്ടത്തിൽ പെടാത്തത് വേഗത്തിൽ കണ്ടെത്തുക:",
        "options": [
            {
                "text": "3F7",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "7F3",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "F37",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "37F",
                "textMl": "",
                "isCorrect": true
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which line has more characters? Line 1: #$#$#$#$ | Line 2: #$#$#$#$",
        "textMl": "ഇതിൽ ഏത് വരിയിലാണ് കൂടുതൽ ചിഹ്നങ്ങൾ ഉള്ളത്? Line 1: #$#$#$#$ | Line 2: #$#$#$#$",
        "options": [
            {
                "text": "Line 1",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Line 2",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "Neither",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "Cannot be determined",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which symbol repeats after exactly 4 positions? [ ● ▲ ■ ◆ ● ]",
        "textMl": "നാല് സ്ഥാനങ്ങൾ കഴിഞ്ഞു വീണ്ടും വരുന്ന ചിഹ്നം ഏതാണ്? [ ● ▲ ■ ◆ ● ]",
        "options": [
            {
                "text": "●",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "▲",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "■",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "◆",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Identify the missing number in the sequence: 2, 4, __, 8, 10",
        "textMl": "ഈ ക്രമത്തിൽ വിട്ടുപോയ സംഖ്യ ഏതാണ്: 2, 4, __, 8, 10",
        "options": [
            {
                "text": "5",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "6",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "7",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "9",
                "textMl": "",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which pair is NOT reversed?",
        "textMl": "ഇതിൽ തിരിച്ചിട്ടിരിക്കാത്ത ജോഡി ഏതാണ്?",
        "options": [
            {
                "text": "MN / NM",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "OP / OP",
                "textMl": "",
                "isCorrect": true
            },
            {
                "text": "QR / RQ",
                "textMl": "",
                "isCorrect": false
            },
            {
                "text": "ST / TS",
                "textMl": "",
                "isCorrect": false
            }
        ]
    }
];
