export const studentAptitudeQuestions = [
    {
        "section": "Numerical Reasoning",
        "text": "A sequence follows this rule: Each term is generated by combining the difference and ratio of the previous two terms alternately.",
        "options": [
            {
                "text": "6",
                "isCorrect": false
            },
            {
                "text": "9",
                "isCorrect": false
            },
            {
                "text": "12",
                "isCorrect": false
            },
            {
                "text": "3",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Four machines together complete a task in 6 hours. Two of them stop after 2 hours. The remaining two finish the task in 10 more hours. Which statement is logically true?",
        "options": [
            {
                "text": "All machines work at equal efficiency (?????",
                "isCorrect": false
            },
            {
                "text": "The stopped machines were faster (???",
                "isCorrect": false
            },
            {
                "text": "Remaining machines are slower than the initial average (???????????",
                "isCorrect": false
            },
            {
                "text": "Cannot be determined (?????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "A number is multiplied by 4, then 12 is subtracted. The result is equal to triple the original number plus 6. What is the number?",
        "options": [
            {
                "text": "6",
                "isCorrect": false
            },
            {
                "text": "9",
                "isCorrect": false
            },
            {
                "text": "12",
                "isCorrect": false
            },
            {
                "text": "18",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Which option completes the pattern? 2 ? 6 ? 18 ? ? ? 162 ?",
        "options": [
            {
                "text": "36",
                "isCorrect": false
            },
            {
                "text": "54",
                "isCorrect": false
            },
            {
                "text": "72",
                "isCorrect": false
            },
            {
                "text": "81",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "If all Zogs are Tals and some Tals are Rims, which is true?",
        "options": [
            {
                "text": "All Zogs are Rims (?????",
                "isCorrect": false
            },
            {
                "text": "Some Zogs may be Rims (???",
                "isCorrect": false
            },
            {
                "text": "No Zogs are Rims (??????",
                "isCorrect": false
            },
            {
                "text": "All Rims are Zogs (?????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "A number increases by 20%, then the result decreases by 20%. The final value is:",
        "options": [
            {
                "text": "Same as original (????????",
                "isCorrect": false
            },
            {
                "text": "Higher (????????????????)",
                "isCorrect": false
            },
            {
                "text": "Lower (??????????????)",
                "isCorrect": false
            },
            {
                "text": "Cannot be predicted (?????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Which option has the same logical structure as: \"Half of X plus one-third of X equals five-sixths of X\"? \"X-????" -",
        "options": [
            {
                "text": "2/4 + 1/6 = 5/6",
                "isCorrect": false
            },
            {
                "text": "3/6 + 2/6 = 5/6",
                "isCorrect": false
            },
            {
                "text": "1/2 + 1/3 = 5/6",
                "isCorrect": false
            },
            {
                "text": "4/6 + 1/6 = 5/6",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "If A > B > C and D < C, which must be true? A",
        "options": [
            {
                "text": "D < A",
                "isCorrect": false
            },
            {
                "text": "D > A",
                "isCorrect": false
            },
            {
                "text": "B < D",
                "isCorrect": false
            },
            {
                "text": "C < A",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "Which situation represents exponential growth?",
        "options": [
            {
                "text": "Salary increases by ?1000 yearly (??????",
                "isCorrect": false
            },
            {
                "text": "Savings double every year (?????????",
                "isCorrect": false
            },
            {
                "text": "Distance increases by 10 km daily (????",
                "isCorrect": false
            },
            {
                "text": "Weight increases linearly (????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Numerical Reasoning",
        "text": "If 5 people complete 40 units of work in 8 days, how many units per person per day? 5",
        "options": [
            {
                "text": "1",
                "isCorrect": false
            },
            {
                "text": "0.8",
                "isCorrect": false
            },
            {
                "text": "1.25",
                "isCorrect": false
            },
            {
                "text": "2",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "All thinkers question assumptions. Some scientists are thinkers. Which is logically valid?",
        "options": [
            {
                "text": "All scientists question assumptions (?????",
                "isCorrect": false
            },
            {
                "text": "Some scientists question assumptions (???",
                "isCorrect": false
            },
            {
                "text": "No scientists question assumptions (???????????????",
                "isCorrect": false
            },
            {
                "text": "All thinkers are scientists (?????????????????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "\"Resilient\" is to \"stress\" as \"elastic\" is to: '??????????' (Resilient)",
        "options": [
            {
                "text": "Pressure (??????)",
                "isCorrect": false
            },
            {
                "text": "Weight (????)",
                "isCorrect": false
            },
            {
                "text": "Stretch (?????)",
                "isCorrect": false
            },
            {
                "text": "Shape (?????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Choose the statement that best completes the argument: \"Critical thinking improves decisions because...\" \"???????????" -",
        "options": [
            {
                "text": "It increases intelligence (???",
                "isCorrect": false
            },
            {
                "text": "It reduces emotions (???",
                "isCorrect": false
            },
            {
                "text": "It evaluates evidence and alternatives (???",
                "isCorrect": false
            },
            {
                "text": "It speeds up thinking (???",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Which sentence weakens the claim: \"Online learning always improves academic outcomes\"? \"?????" - ?",
        "options": [
            {
                "text": "Some students prefer classroom learning (???",
                "isCorrect": false
            },
            {
                "text": "Internet access varies across regions (???????????",
                "isCorrect": false
            },
            {
                "text": "Motivation affects learning (?????????",
                "isCorrect": false
            },
            {
                "text": "Teachers use different methods (???",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Identify the odd relationship:",
        "options": [
            {
                "text": "Doctor : Hospital (?????? :",
                "isCorrect": false
            },
            {
                "text": "Teacher : School (?????? :",
                "isCorrect": false
            },
            {
                "text": "Pilot : Airport (??????? :",
                "isCorrect": false
            },
            {
                "text": "Farmer : Crops (????? :",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Which assumption is necessary? \"Company profits rose after flexible work hours were introduced.\" \"????" - ?",
        "options": [
            {
                "text": "Employees worked fewer hours (?????????",
                "isCorrect": false
            },
            {
                "text": "Flexible hours improve productivity (????",
                "isCorrect": false
            },
            {
                "text": "No other external changes occurred (????",
                "isCorrect": false
            },
            {
                "text": "Profits always rise (????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Choose the strongest inference: \"Most creative people experiment frequently.\" \"???????????????? (Creative)" -",
        "options": [
            {
                "text": "All experimenters are creative (???????????",
                "isCorrect": false
            },
            {
                "text": "Creativity requires experimentation (???????????",
                "isCorrect": false
            },
            {
                "text": "Experimentation is linked to creativity (??????????????",
                "isCorrect": false
            },
            {
                "text": "Creativity is rare (??????????????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Which sentence contradicts: \"Efficiency requires careful planning\"? \"??????" -",
        "options": [
            {
                "text": "Planning reduces errors (?????????",
                "isCorrect": false
            },
            {
                "text": "Efficiency improves speed (??????????",
                "isCorrect": false
            },
            {
                "text": "Careless work is inefficient (???????????????",
                "isCorrect": false
            },
            {
                "text": "Efficiency can exist without planning (?????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Which pair shares the same relationship? Idea : Innovation '???? :",
        "options": [
            {
                "text": "Seed : Plant (?????? :",
                "isCorrect": false
            },
            {
                "text": "Plan : Success (????? :",
                "isCorrect": false
            },
            {
                "text": "Theory : Practice (?????????? :",
                "isCorrect": false
            },
            {
                "text": "Word : Sentence (?????? :",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Verbal Reasoning",
        "text": "Which conclusion follows logically? \"If data is inaccurate, conclusions may be flawed.\" \"????????" -",
        "options": [
            {
                "text": "Accurate data guarantees success (??????",
                "isCorrect": false
            },
            {
                "text": "Flawed conclusions come only from bad data (???????",
                "isCorrect": false
            },
            {
                "text": "Data accuracy affects reliability (???????????",
                "isCorrect": false
            },
            {
                "text": "Data is always reliable (????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which shape completes the pattern? ?",
        "options": [
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "�",
                "isCorrect": false
            },
            {
                "text": "?",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If follows a rule, which comes next? ?",
        "options": [
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "Both (??????",
                "isCorrect": false
            },
            {
                "text": "Cannot be determined (?????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which option does NOT belong?",
        "options": [
            {
                "text": "? (Triangle)",
                "isCorrect": false
            },
            {
                "text": "? (Pentagon)",
                "isCorrect": false
            },
            {
                "text": "? (Hexagon)",
                "isCorrect": false
            },
            {
                "text": "? (Circle)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If A ? C, B ? D, C ? F, then D ? ? A",
        "options": [
            {
                "text": "G",
                "isCorrect": false
            },
            {
                "text": "H",
                "isCorrect": false
            },
            {
                "text": "I",
                "isCorrect": false
            },
            {
                "text": "J",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Square : Cube :: Circle : ?",
        "options": [
            {
                "text": "Sphere (??????)",
                "isCorrect": false
            },
            {
                "text": "Cone (???)",
                "isCorrect": false
            },
            {
                "text": "Cylinder (????????)",
                "isCorrect": false
            },
            {
                "text": "Oval (???)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If pattern complexity doubles every step, which option fits next?",
        "options": [
            {
                "text": "+",
                "isCorrect": false
            },
            {
                "text": "++",
                "isCorrect": false
            },
            {
                "text": "++++",
                "isCorrect": false
            },
            {
                "text": "++++++",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which option completes the sequence of transformations? Rotate ? Flip ? Rotate ? ?",
        "options": [
            {
                "text": "Flip (????????)",
                "isCorrect": false
            },
            {
                "text": "Scale (???????",
                "isCorrect": false
            },
            {
                "text": "Reflect (?????????)",
                "isCorrect": false
            },
            {
                "text": "Reverse (???????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "If all Blips are Plips and no Plips are Slips, which is true?",
        "options": [
            {
                "text": "Some Blips are Slips (???",
                "isCorrect": false
            },
            {
                "text": "No Blips are Slips (??????????",
                "isCorrect": false
            },
            {
                "text": "All Slips are Blips (?????",
                "isCorrect": false
            },
            {
                "text": "Some Slips are Blips (???",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which pattern uses two simultaneous rules?",
        "options": [
            {
                "text": "? � ? �",
                "isCorrect": false
            },
            {
                "text": "2, 4, 6, 8",
                "isCorrect": false
            },
            {
                "text": "A, C, E, G",
                "isCorrect": false
            },
            {
                "text": "? ? � �",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Abstract-Fluid Reasoning",
        "text": "Which option best completes a novel, unfamiliar rule set?",
        "options": [
            {
                "text": "Option with symmetry (???????????",
                "isCorrect": false
            },
            {
                "text": "Option with repetition (????????????",
                "isCorrect": false
            },
            {
                "text": "Option with balanced variation (????????",
                "isCorrect": false
            },
            {
                "text": "Option with randomness (?????????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which object results from rotating a cube 90� vertically?",
        "options": [
            {
                "text": "Same faces visible (???",
                "isCorrect": false
            },
            {
                "text": "Opposite faces visible (??????????",
                "isCorrect": false
            },
            {
                "text": "Adjacent faces visible (??????????",
                "isCorrect": false
            },
            {
                "text": "One face disappears (???",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "If a folded paper with two holes is unfolded, how many holes appear?",
        "options": [
            {
                "text": "2",
                "isCorrect": false
            },
            {
                "text": "4",
                "isCorrect": false
            },
            {
                "text": "6",
                "isCorrect": false
            },
            {
                "text": "8",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which net forms a cube?",
        "options": [
            {
                "text": "Cross-shaped net (??????????",
                "isCorrect": false
            },
            {
                "text": "Straight strip of 6 squares (???",
                "isCorrect": false
            },
            {
                "text": "Zigzag pattern (????-????",
                "isCorrect": false
            },
            {
                "text": "Random arrangement (?????????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which shape is a mirror image of a right-facing 'L'?",
        "options": [
            {
                "text": "Same 'L' (???????)",
                "isCorrect": false
            },
            {
                "text": "Reversed 'L' (??????????",
                "isCorrect": false
            },
            {
                "text": "Upside down 'L' (????????? 'L')",
                "isCorrect": false
            },
            {
                "text": "Circle (??????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "If a staircase is viewed from directly above, what shape appears?",
        "options": [
            {
                "text": "Triangle (????????)",
                "isCorrect": false
            },
            {
                "text": "Spiral (??????)",
                "isCorrect": false
            },
            {
                "text": "Rectangle/Grid (????????/??????)",
                "isCorrect": false
            },
            {
                "text": "Circle (??????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which direction results after: North ? Right ? Left ? Right?",
        "options": [
            {
                "text": "North (??????)",
                "isCorrect": false
            },
            {
                "text": "East (???????)",
                "isCorrect": false
            },
            {
                "text": "South (??????)",
                "isCorrect": false
            },
            {
                "text": "West (?????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which solid has the most edges?",
        "options": [
            {
                "text": "Cube (??????)",
                "isCorrect": false
            },
            {
                "text": "Pyramid (???????)",
                "isCorrect": false
            },
            {
                "text": "Sphere (??????)",
                "isCorrect": false
            },
            {
                "text": "Cylinder (????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "If a point light source is directly above a cone, what is the shape of the shadow?",
        "options": [
            {
                "text": "Triangle (????????)",
                "isCorrect": false
            },
            {
                "text": "Square (?????)",
                "isCorrect": false
            },
            {
                "text": "Circle (??????)",
                "isCorrect": false
            },
            {
                "text": "Rectangle (?????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which arrangement fits a space exactly without gaps or overlaps?",
        "options": [
            {
                "text": "Overlapping shapes (?????????????",
                "isCorrect": false
            },
            {
                "text": "Gaps between shapes (?????",
                "isCorrect": false
            },
            {
                "text": "Perfect tessellation (?????????",
                "isCorrect": false
            },
            {
                "text": "Random placement (?????????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Spatial Ability",
        "text": "Which transformation moves a shape's position without altering its orientation or view?",
        "options": [
            {
                "text": "Translation (????????????)",
                "isCorrect": false
            },
            {
                "text": "Reflection (?????????)",
                "isCorrect": false
            },
            {
                "text": "Rotation (????????)",
                "isCorrect": false
            },
            {
                "text": "Scaling (???????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If Gear A turns clockwise, Gear B (connected directly) turns:",
        "options": [
            {
                "text": "Clockwise (????????",
                "isCorrect": false
            },
            {
                "text": "Anti-clockwise (????",
                "isCorrect": false
            },
            {
                "text": "Faster (??????",
                "isCorrect": false
            },
            {
                "text": "Slower (???????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which tool best increases force with less effort?",
        "options": [
            {
                "text": "Lever (????)",
                "isCorrect": false
            },
            {
                "text": "Rope (???)",
                "isCorrect": false
            },
            {
                "text": "Wheel (?????)",
                "isCorrect": false
            },
            {
                "text": "Pulley (??????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If water flows faster through a narrow pipe, the relative pressure:",
        "options": [
            {
                "text": "Increases (????????)",
                "isCorrect": false
            },
            {
                "text": "Decreases (?????????)",
                "isCorrect": false
            },
            {
                "text": "Remains same (?????????????",
                "isCorrect": false
            },
            {
                "text": "Stops (???????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which setup lifts a load most efficiently?",
        "options": [
            {
                "text": "Single rope (?????",
                "isCorrect": false
            },
            {
                "text": "Fixed pulley (?????????",
                "isCorrect": false
            },
            {
                "text": "Movable pulley system (??????????",
                "isCorrect": false
            },
            {
                "text": "No pulley (??????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If friction increases between two surfaces, motion becomes:",
        "options": [
            {
                "text": "Faster (????",
                "isCorrect": false
            },
            {
                "text": "Unchanged (??????????)",
                "isCorrect": false
            },
            {
                "text": "Harder (???????????????)",
                "isCorrect": false
            },
            {
                "text": "Impossible (?????????????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which factor affects structural stability most?",
        "options": [
            {
                "text": "Height (????)",
                "isCorrect": false
            },
            {
                "text": "Base width and Center of Gravity (???????????",
                "isCorrect": false
            },
            {
                "text": "Color (????)",
                "isCorrect": false
            },
            {
                "text": "Material (??????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If one support fails in a redundant structure, what happens?",
        "options": [
            {
                "text": "Stable (???????",
                "isCorrect": false
            },
            {
                "text": "Collapses partially/Redistributes load (?????????",
                "isCorrect": false
            },
            {
                "text": "Stronger (??????",
                "isCorrect": false
            },
            {
                "text": "Unchanged (??????????)",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which increases speed without increasing input effort?",
        "options": [
            {
                "text": "Heavier load (??????",
                "isCorrect": false
            },
            {
                "text": "Better alignment/Lower friction (????????",
                "isCorrect": false
            },
            {
                "text": "Rough surface (?????????",
                "isCorrect": false
            },
            {
                "text": "Smaller wheel (?????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "If energy is conserved, efficiency losses typically occur as:",
        "options": [
            {
                "text": "Light only (????????",
                "isCorrect": false
            },
            {
                "text": "Sound only (?????",
                "isCorrect": false
            },
            {
                "text": "Heat and sound (?????",
                "isCorrect": false
            },
            {
                "text": "Mass disappearing (??????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Mechanical Reasoning",
        "text": "Which change improves system output most effectively?",
        "options": [
            {
                "text": "Random adjustment (????????????",
                "isCorrect": false
            },
            {
                "text": "Reducing friction (????",
                "isCorrect": false
            },
            {
                "text": "Increasing weight (????",
                "isCorrect": false
            },
            {
                "text": "Increasing resistance (?????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Identify the matching pair quickly:",
        "options": [
            {
                "text": "AB-BA",
                "isCorrect": false
            },
            {
                "text": "AC-CA",
                "isCorrect": false
            },
            {
                "text": "AB-AC",
                "isCorrect": false
            },
            {
                "text": "BA-CA",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which symbol appears most frequently in this set ?",
        "options": [
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "�",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which number breaks the pattern? ?",
        "options": [
            {
                "text": "21",
                "isCorrect": false
            },
            {
                "text": "28",
                "isCorrect": false
            },
            {
                "text": "35",
                "isCorrect": false
            },
            {
                "text": "43",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Count the total triangles in a standard six-pointed star.",
        "options": [
            {
                "text": "6",
                "isCorrect": false
            },
            {
                "text": "8",
                "isCorrect": false
            },
            {
                "text": "10",
                "isCorrect": false
            },
            {
                "text": "12",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which pair is identical?",
        "options": [
            {
                "text": "AX9 / A9X",
                "isCorrect": false
            },
            {
                "text": "B7C / B7C",
                "isCorrect": false
            },
            {
                "text": "9XA / XA9",
                "isCorrect": false
            },
            {
                "text": "C8B / 8CB",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Spot the odd one quickly:",
        "options": [
            {
                "text": "3F7",
                "isCorrect": false
            },
            {
                "text": "7F3",
                "isCorrect": false
            },
            {
                "text": "F37",
                "isCorrect": false
            },
            {
                "text": "37F",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which line has more characters?",
        "options": [
            {
                "text": "Line 1",
                "isCorrect": false
            },
            {
                "text": "Line 2",
                "isCorrect": false
            },
            {
                "text": "Neither (??????",
                "isCorrect": false
            },
            {
                "text": "Cannot be determined (????????????????",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which symbol repeats after exactly 4 positions?",
        "options": [
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "?",
                "isCorrect": false
            },
            {
                "text": "�",
                "isCorrect": false
            },
            {
                "text": "?",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Identify the missing number in the sequence: 2, 4, __, 8, 10 ?",
        "options": [
            {
                "text": "5",
                "isCorrect": false
            },
            {
                "text": "6",
                "isCorrect": false
            },
            {
                "text": "7",
                "isCorrect": false
            },
            {
                "text": "9",
                "isCorrect": false
            }
        ]
    },
    {
        "section": "Processing Speed & Accuracy",
        "text": "Which pair is reversed?",
        "options": [
            {
                "text": "MN / NM",
                "isCorrect": false
            },
            {
                "text": "OP / OP",
                "isCorrect": false
            },
            {
                "text": "QR / RQ",
                "isCorrect": false
            },
            {
                "text": "ST / TS",
                "isCorrect": false
            }
        ]
    }
];
